version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      safe-updates:
        update-types: ["patch", "minor"]
    commit-message:
      prefix: "chore(deps)"
